# This is only used for CI. You should not need to run `dev up` locally.
up:
  - node:
      version: v16.5.0
      yarn: 1.22.5

commands:
  server:
    run: yarn dev-server
    desc: 'Start the web server'

  lib:
    run: yarn dev-lib
    desc: 'Start the library dev server'

  build:
    run: yarn build
    desc: Run the build process for lib and dev'

  test:
    run: yarn test;
    desc: 'Run tests using Jest'

  coverage:
    run: yarn test:coverage; open coverage/index.html;
    desc: 'Run tests using Jest, collect coverage and open in-browser coverage report'

open:
  app: http://localhost:3000
