export const CUSTOMER_ACCESS_TOKEN_COOKIE_NAME = 'secure_customer_sig';
export const CUSTOMER_ACCESS_TOKEN_EXPIRE_NAME = `${CUSTOMER_ACCESS_TOKEN_COOKIE_NAME}_expires`;
export const CUSTOMER_ACCESS_TOKEN_REMEMBER_NAME = `${CUSTOMER_ACCESS_TOKEN_COOKIE_NAME}_remembered`;
