name: Discord announcement

on:
  release:
    types: [published]

jobs:
  build:
    if: startsWith(github.event.release.tag_name, '@shopify/hydrogen@')
    runs-on: ubuntu-latest

    steps:
      - name: Set Hydrogen version as env
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "HYDROGEN_VERSION=${TAG//@shopify\/hydrogen@/}" >> $GITHUB_ENV

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Shopify Devs
          DISCORD_AVATAR: https://cdn.discordapp.com/avatars/905537246990590012/0f6a687b93ef3f81a036c817fb02ccbf.webp
        uses: Ilshidur/action-discord@08d9328877d6954120eef2b07abbc79249bb6210
        with:
          args: "Hydrogen ${{ env.HYDROGEN_VERSION }} has been released.\n${{ github.event.release.html_url }}"
